### ISSUE TITLE
Weird entry in google index

### ISSUE THREAD

**Issue by reederz** [fadeit/fadeitdk-blog#22]
![google-stuff](https://cloud.githubusercontent.com/assets/3193560/18226425/b3f1c540-7209-11e6-8b05-1a4117ca1e9c.png)

**Comment by danmindru** [comment]
I think it's just an old index; crawling the page through webmaster tools seems OK.
This kind of indexing happens when there's no `<title>` at all, and the spider just crawls whatever bits of text she finds interesting. Maybe that was the case when you first deployed the new blog.

**I've disabled automatic title generation via the jekyll seo plugin though, probably everything will be fine when it'll be crawled again.**

As a reference, the seo plugin appended the site description to each title (way longer than the  recommended 50-60 chars). Not a good idea to re-enable it in the future.

**Comment by reederz** [comment]
@danmindru you're right. Gonna close this issue.
